# 开发环境
server:
  port: 8080
spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_startup
    username: root
    password: root
  # redis配置
  redis:
    host: localhost
    port: 6379
    database: 0
  # 邮箱配置
  mail:
    host: smtp.qq.com
    username: bearvideo@qq.com
    password: pcppmdkdyxdnhgef
mybatis-plus:
  configuration:
    # log日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
project:
  # 项目路径
  path: D:/workspace/smartSQL