# 公共配置
server:
  # 否则其他电脑无法通过http访问
  address: 0.0.0.0
  # 访问路径
  servlet:
    context-path: /api
spring:
  application:
    name: smartSQL
  profiles:
    active: dev
  servlet:
    multipart:
      # 单个文件大小限制
      max-file-size: 10MB
      max-request-size: 15MB
  # session配置
  session:
    # 1天过期
    timeout: 86400
    # 分布式session store-type: redis
    store-type: none
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: is_delete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值